---

image: "reporunner/golang-alpine"
checkout_dir: /go/src/github.com/Luzifer/share

commands:
  - make publish

environment:
  DRAFT: "false"
  CGO_ENABLED: 0
  GO111MODULE: on
  MOD_MODE: readonly
